<?php 
	# Styles
	$this->headLink()->appendStylesheet($this->basePath() . '/css/user/criar-conta.css');

	# Scripts
	$this->inlineScript()->appendFile($this->basePath() . '/js/bootstrap-select.js')
						 ->appendFile($this->basePath() . '/js/flatui-radio.js')
						 ->appendFile($this->basePath() . '/js/flatui-checkbox.js')
						 ->appendFile($this->basePath() . '/js/application.js')
						 ->appendFile($this->basePath() . '/js/jquery.maskedinput.js')
						 ->appendFile($this->basePath() . '/js/user/criar-conta.js');

	# Configuração do form
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('action', $this->url('criar-conta'));
?>

<article id="main" class="create-account inside">
	<div class="container">

		<h2>Cadastre-se</h2>
		<p>Crie uma conta ou se preferir use seu login do <a href="javascript:void(0);">Facebook</a>.</p>
		
		<?php echo $this->form()->openTag($form); ?>
			<fieldset>
				<legend>Dados Pessoais</legend>

				<div class="clearfix">
					<?php 
						echo $this->formLabel($form->get('tipo_conta'));
						echo $this->formSelect($form->get('tipo_conta'));
					?>
				</div>

				<div class="span8 inline-block no-margin mleft">
					<?php 
						echo $this->formLabel($form->get('nome'));
						echo $this->formText($form->get('nome'));
					?>
				</div>

				<div class="span3 inline-block">
					<label>Sexo</label>								
			    	<label class="radio inline-block">
		            	<span class="icons">
		            		<span class="first-icon fui-radio-unchecked"></span>
		            		<span class="second-icon fui-radio-checked"></span>
		            	</span>
		            	<input type="radio" data-toggle="radio" value="M" name="sexo"> Masculino
		          	</label>
		          	<label class="radio inline-block">
		            	<span class="icons">
		            		<span class="first-icon fui-radio-unchecked"></span>
		            		<span class="second-icon fui-radio-checked"></span>
		            	</span>
		            	<input type="radio" data-toggle="radio" value="F" name="sexo"> Feminino
		          	</label>
					<input id="hiddenSexo" type="hidden" name="sexo" value="" />
				</div>
			</fieldset>

			<fieldset>
				<div class="span2 inline-block no-margin mleft">
					<?php echo $this->formLabel($form->get('data_nasc'));
						  echo $this->formText($form->get('data_nasc')); ?>
				</div>

				<div class="span6 inline-block">
					<?php echo $this->formLabel($form->get('email'));
						  echo $this->formText($form->get('email')); ?>
				</div>
			</fieldset>

			<fieldset>
				<legend>Contato</legend>

				<div class="span3 inline-block no-margin mleft">
					<?php echo $this->formLabel($form->get('telefone'));
						  echo $this->formText($form->get('telefone')); ?>
				</div>

				<div class="span3 inline-block">
					<?php echo $this->formLabel($form->get('celular'));
						  echo $this->formText($form->get('celular')); ?>
				</div>
			</fieldset>

			<fieldset>
				<legend>Endereço</legend>

				<?php echo $this->formLabel($form->get('cep'));
					  echo $this->formText($form->get('cep')); ?>
			</fieldset>

			<fieldset>
				<div class="span8 inline-block no-margin mleft">
					<?php echo $this->formLabel($form->get('endereco'));
					 	  echo $this->formText($form->get('endereco')); ?>
				</div>

				<div class="span2 inline-block">
					<?php echo $this->formLabel($form->get('numero'));
						  echo $this->formText($form->get('numero')); ?>
				</div>
			</fieldset>

			<fieldset>
				<div class="span4 inline-block no-margin mleft">
					<?php echo $this->formLabel($form->get('complemento'));
						  echo $this->formText($form->get('complemento')); ?>
				</div>

				<div class="span4 inline-block">
					<?php echo $this->formLabel($form->get('bairro'));
						  echo $this->formText($form->get('bairro')); ?>
				</div>
			</fieldset>

			<fieldset>
				<div class="span4 inline-block no-margin mleft">
					<?php echo $this->formLabel($form->get('cidade'));
						  echo $this->formText($form->get('cidade')); ?>
				</div>

				<div class="span2 inline-block">
					<?php echo $this->formLabel($form->get('estado'));
						  echo $this->formSelect($form->get('estado')); ?>
				</div>
			</fieldset>

			<fieldset>
				<legend>Acesso</legend>
				<div class="span4 inline-block no-margin mleft">
					<?php echo $this->formLabel($form->get('senha'));
						  echo $this->formText($form->get('senha')); ?>
				</div>

				<div class="span4 inline-block">
					<?php echo $this->formLabel($form->get('confirmar_senha'));
					 	  echo $this->formText($form->get('confirmar_senha')); ?>
				</div>
			</fieldset>

			<fieldset>
				<label class="checkbox agree">
					<span class="icons">
						<span class="first-icon fui-checkbox-unchecked"></span>
						<span class="second-icon fui-checkbox-checked"></span>
					</span>
					<?php echo $this->formCheckbox($form->get('noticicacoes'));
						  echo $this->formLabel($form->get('noticicacoes')); ?>
				</label>
		    </fieldset>

		    <?php echo $this->formSubmit($form->get('cadastrar')); ?>
		    <button class="btn btn-large span2 pull-right" type="reset">Cancelar</button>

		<?php  echo $this->form()->closeTag(); ?>
</article>