<?php 
	# Styles
	$this->headLink()->appendStylesheet($this->basePath() . '/css/user/minha-conta.css');

	# Scripts
	$this->inlineScript()->appendFile($this->basePath() . '/js/bootstrap-select.js')
						 ->appendFile($this->basePath() . '/js/flatui-radio.js')
						 ->appendFile($this->basePath() . '/js/flatui-checkbox.js')
						 ->appendFile($this->basePath() . '/js/application.js');
?>


<article id="main" class="create-account inside">
	<div class="container">

		<h2>Minha conta</h2>
	</div>
</article>