<?php echo $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(PROJECT_NAME)->setSeparator(' | ')->setAutoEscape(false) ?>

        <!-- Favicon -->
        <?php # echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')) ?>

        <!-- Styles -->
        <?php  $this->headLink()->prependStylesheet($this->basePath() . '/css/flat-ui.css')
                                ->prependStylesheet($this->basePath() . '/css/bootstrap.css'); ?>

        <?php echo $this->headLink() ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>

        <!-- header -->
        <header id="header">
            <div class="container">
                <h1>
                    <?php if ($this->identifyRoute() != "home") : ?>
                        <a href="<?php echo $this->url('home') ?>">
                            <span class="fui-search"></span>
                            <?php echo PROJECT_NAME; ?>
                        </a>
                    <?php else : ?>
                        <span class="fui-search"></span>
                        <?php echo PROJECT_NAME; ?>
                    <?php endif; ?>
                </h1>

                <div class="navbar navbar-inverse pull-right">
                    <div class="navbar-inner">
                        <div id="nav-collapse-01" class="nav-collapse collapse">
                            <?php echo $this->navigation('navigation')
                                            ->menu()
                                            ->setPartial(array('layout/navigation.phtml', 'default'))
                                            ->render(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </header><!-- /header -->


        <?php
            if ($this->identifyRoute() != "home") :
                echo $this->navigation('Navigation')
                          ->breadcrumbs()
                          ->setMinDepth(0)
                          ->setPartial(array('layout/breadcrumbs.phtml', 'default'))
                          ->render();
            endif;
        ?>

        <?php echo $this->content; ?>

        <footer id="footer">
            <div class="container">
                <div class="row">
                    <div class="span5 pull-right part-footer">
                        <p class="text-center"><?php echo COPY; ?></p>
                    </div>
                </div>
            </div>
        </footer>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
